name: Cobertura de Código

on:
  pull_request:

jobs:
  build:
    name: Cobertura de Código
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Configurando ambiente Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalação do Diff-Cover
        run: pip install diff_cover

      - name: Configurando JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build e test report JaCoCo com Maven
        run: mvn -B test
  
      - name: Run Diff Cover
        run: |
          echo "Roda diff-cover com o report gerado anteriormente. Comparação com a branch ${{ github.base_ref }}"
          diff-cover target/site/jacoco/jacoco.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=80

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          retention-days: 1
          path: |
            target/site/jacoco/jacoco.xml

          
          