name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v2

      
      - name: Configurando ambiente Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Instalação do Diff-Cover
        run: pip install diff_cover

      - name: Configurando JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build e test report JaCoCo com Maven
        run: mvn -B test

      - name: Run Diff Cover
        run: diff-cover target/site/jacoco/jacoco.xml --compare-branch=${{ github.base_ref }} --fail-under=80

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: target/site/jacoco/
          